modules/task_1/ognev_d_markings_hulls/CMakeLists.txt
modules/task_1/ognev_d_markings_hulls/main.cpp
modules/task_1/ognev_d_markings_hulls/markings_hulls.cpp
modules/task_1/ognev_d_markings_hulls/markings_hulls.h

Реализовано разбиение бинарного изображения на компоненты и построение выпуклых оболочек полученных компонент.

Огнев Денис. Задача 1. Построение выпуклой оболочки для компонент бинарного изображения.

---

modules/task_2/kochankov_i_shell_sort_simple_omp/CMakeLists.txt
modules/task_2/kochankov_i_shell_sort_simple_omp/main.cpp
modules/task_2/kochankov_i_shell_sort_simple_omp/shell_sort_simple_omp.cpp
modules/task_2/kochankov_i_shell_sort_simple_omp/shell_sort_simple_omp.h

Сортировка Шелла (англ. Shell sort) — алгоритм сортировки, являющийся усовершенствованным вариантом сортировки вставками. Идея метода Шелла состоит в сравнении элементов, стоящих не только рядом, но и на определённом расстоянии друг от друга.
OMP версия

Кочанков Илья. Задача 2. Сортировка Шелла простым слиянием

---

modules/task_1/zlobin_g_sparse_matrix_ccs_mult_complex/CMakeLists.txt
modules/task_1/zlobin_g_sparse_matrix_ccs_mult_complex/main.cpp
modules/task_1/zlobin_g_sparse_matrix_ccs_mult_complex/matrix_ccs_mult.cpp
modules/task_1/zlobin_g_sparse_matrix_ccs_mult_complex/matrix_ccs_mult.h

Злобин Георгий. Задача 1. Умножение разреженных матриц. Элементы комплексного типа. Формат хранения матрицы – столбцовый (CCS).

---

modules/task_1/kokh_v_hoar_sort_batcher/CMakeLists.txt
modules/task_1/kokh_v_hoar_sort_batcher/hoar_sort_batcher.cpp
modules/task_1/kokh_v_hoar_sort_batcher/hoar_sort_batcher.h
modules/task_1/kokh_v_hoar_sort_batcher/main.cpp

Кох Владислав. Задача 1. Сортировка Хоара с четно-нечетным слиянием Бэтчера.

Кох Владислав. Задача 1. Сортировка Хоара с четно-нечетным слиянием Бэтчера.

---

modules/task_1/evseev_a_gauss/CMakeLists.txt
modules/task_1/evseev_a_gauss/evseev_a_gauss.cpp
modules/task_1/evseev_a_gauss/evseev_a_gauss.h
modules/task_1/evseev_a_gauss/main.cpp

Евсеев Александр. Задача 1. Линейная фильтрация изображений (горизонтальное разбиение). Ядро Гаусса 3x3.

---

modules/task_1/vizgalov_a_hoare_sort_simple_merge/CMakeLists.txt
modules/task_1/vizgalov_a_hoare_sort_simple_merge/hoare_sort_simple_merge.cpp
modules/task_1/vizgalov_a_hoare_sort_simple_merge/hoare_sort_simple_merge.h
modules/task_1/vizgalov_a_hoare_sort_simple_merge/main.cpp

**Реализовано:**
- QuickSort
- функция для "слияния" двух массивов
- разделение массива на сегменты, сортировка сегментов и последующее слияние (заготовка под параллельную версию)
- генератор нескольких типов массивов с рандомными числами

Визгалов Антон. Задача 1. Сортировка Хоара с простым слиянием.

---

modules/task_1/pasukhin_d_crs/crs.cpp
modules/task_1/pasukhin_d_crs/crs.h
modules/task_1/pasukhin_d_crs/main.cpp

Исправление типа данных, хранимых в матрице с обычного double -> complex<double>

Пасухин Дмитрий. Задача 1.Умножение разреженных матриц. Элементы комплексного типа. Формат хранения матрицы – строковый (Исправление)

---

modules/task_2/kochankov_i_shell_sort_simple_omp/shell_sort_simple_omp.cpp
modules/task_3/kochankov_i_shell_sort_simple_tbb/CMakeLists.txt
modules/task_3/kochankov_i_shell_sort_simple_tbb/main.cpp
modules/task_3/kochankov_i_shell_sort_simple_tbb/shell_sort_simple_tbb.cpp
modules/task_3/kochankov_i_shell_sort_simple_tbb/shell_sort_simple_tbb.h

Сортировка Шелла (англ. Shell sort) — алгоритм сортировки, являющийся усовершенствованным вариантом сортировки вставками. Идея метода Шелла состоит в сравнении элементов, стоящих не только рядом, но и на определённом расстоянии друг от друга.

Кочанков Илья. Задача 3. Сортировка Шелла простым слиянием

---

modules/task_2/zlobin_g_sparse_matrix_ccs_mult_complex_omp/CMakeLists.txt
modules/task_2/zlobin_g_sparse_matrix_ccs_mult_complex_omp/main.cpp
modules/task_2/zlobin_g_sparse_matrix_ccs_mult_complex_omp/matrix_ccs_mult.cpp
modules/task_2/zlobin_g_sparse_matrix_ccs_mult_complex_omp/matrix_ccs_mult.h

Злобин Георгий. Задача 2. Умножение разреженных матриц. Элементы комплексного типа. Формат хранения матрицы – столбцовый (CCS).

---

modules/task_1/rachin_i_lin_hist_stret/CMakeLists.txt
modules/task_1/rachin_i_lin_hist_stret/lin_hist_stret.cpp
modules/task_1/rachin_i_lin_hist_stret/lin_hist_stret.h
modules/task_1/rachin_i_lin_hist_stret/main.cpp

Reverts allnes/pp_2021_spring_engineers#94

Revert "Revert "Рачин Игорь. Задача 1. Повышение контраста полутонового изображения посредством линейной растяжки гистограммы.""

---

modules/task_2/vizgalov_a_hoare_sort_simple_merge/CMakeLists.txt
modules/task_2/vizgalov_a_hoare_sort_simple_merge/hoare_sort_simple_merge.cpp
modules/task_2/vizgalov_a_hoare_sort_simple_merge/hoare_sort_simple_merge.h
modules/task_2/vizgalov_a_hoare_sort_simple_merge/main.cpp

Модифицированное решение задачи 1. Теперь разделенный массив сортируется параллельно в нескольких потоках, а затем отсортированные части сливаются.

Визгалов Антон. Задача 2. Сортировка Хоара с простым слиянием.

---

modules/task_1/bourmistrova_e_tr_int/main.cpp
modules/task_1/bourmistrova_e_tr_int/trapezoid_integral.cpp
modules/task_1/bourmistrova_e_tr_int/trapezoid_integral.h

Бурмистрова Екатерина. Задача 1. Вычисление многомерных интегралов с использованием многошаговой схемы (метод трапеций).

---

modules/task_3/ognev_d_markings_hulls_tbb/CMakeLists.txt
modules/task_3/ognev_d_markings_hulls_tbb/main.cpp
modules/task_3/ognev_d_markings_hulls_tbb/markings_hulls_tbb.cpp
modules/task_3/ognev_d_markings_hulls_tbb/markings_hulls_tbb.h

Реализовано разбиение бинарного изображения на компоненты и построение выпуклых оболочек полученных компонент.

Огнев Денис. Задача 3. Построение выпуклой оболочки для компонент бинарного изображения.

---

modules/task_1/alekhin_d_simpson/main.cpp

Reverts allnes/pp_2021_spring_engineers#17
@AlehinDenis 
https://github.com/allnes/pp_2021_spring_engineers/pull/159/checks?check_run_id=2577808014

Revert "Алехин Денис. Задача 1. Сумма элементов вектора. Вычисление многомерных интегралов с использованием многошаговой схемы (метод Симпсона)."

---

modules/task_2/rukhovich_i_csr_mult_double/CMakeLists.txt
modules/task_2/rukhovich_i_csr_mult_double/csr_mult_double.cpp
modules/task_2/rukhovich_i_csr_mult_double/csr_mult_double.h
modules/task_2/rukhovich_i_csr_mult_double/main.cpp

На компьютере с
Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Удалось получить следующее ускорение:
Размер матриц: 255*255, плотные (в CSR представлении)
| Threads         | 1    | 2    | 4    | 8    | 16   |
| --------------- | ---- | ---- | ---- | ---- | ---- |
| Time, s         | 0.259| 0.135| 0.073| 0.072| 0.073|
| Speed up, ratio | 1.000| 1.924| 3.537| 3.571| 3.555|
Размер матриц: 255*255, заполнены примерно на 1/3
| Threads         | 1    | 2    | 4    | 8    | 16   |
| --------------- | ---- | ---- | ---- | ---- | ---- |
| Time, s         | 0.175| 0.092| 0.051| 0.050| 0.051|
| Speed up, ratio | 1.000| 1.910| 3.451| 3.474| 3.467|

Рухович Игорь. Задача 2. Умножение CSR матриц. формат double, OMP-реализация

---

3rdparty/unapproved/unapproved.h
modules/task_4/rukhovich_i_csr_mult_double/CMakeLists.txt
modules/task_4/rukhovich_i_csr_mult_double/csr_mult_double.cpp
modules/task_4/rukhovich_i_csr_mult_double/csr_mult_double.h
modules/task_4/rukhovich_i_csr_mult_double/main.cpp

На компьютере с
Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Удалось получить следующее ускорение:
Размер матриц: 255*255, плотные (в CSR представлении)
| Threads         | 1    | 2    | 4    | 8    | 16   |
| --------------- | ---- | ---- | ---- | ---- | ---- |
| Time, ms         | 278.542| 143.900| 75.989| 75.781| 76.994|
| Speed up, ratio | 1.000| 1.936| 3.666| 3.676| 3.618|
Размер матриц: 255*255, заполнены примерно на 1/3
| Threads         | 1    | 2    | 4    | 8    | 16   |
| --------------- | ---- | ---- | ---- | ---- | ---- |
| Time, ms         | 184.699| 95.932| 51.181| 51.492| 53.016|
| Speed up, ratio | 1.000| 1.925| 3.609| 3.587| 3.484|

Рухович Игорь. Задача 4. Умножение CSR матриц. формат double, STD-реализация

---

modules/task_2/ptitsyn_p_bbb_sort_omp/CMakeLists.txt
modules/task_2/ptitsyn_p_bbb_sort_omp/bbb_sort.cpp
modules/task_2/ptitsyn_p_bbb_sort_omp/bbb_sort.h
modules/task_2/ptitsyn_p_bbb_sort_omp/main.cpp

Птицын Павел. Задача 2. Поразрядная сортировка для вещественных чисел (тип double) с четно-нечетным слиянием Бэтчера.ptitsyn_p_bbb_sort_omp

---

modules/task_3/ptitsyn_p_bbb_sort_tbb/CMakeLists.txt
modules/task_3/ptitsyn_p_bbb_sort_tbb/bbb_sort.cpp
modules/task_3/ptitsyn_p_bbb_sort_tbb/bbb_sort.h
modules/task_3/ptitsyn_p_bbb_sort_tbb/main.cpp

Птицын Павел. Задача 3. Поразрядная сортировка для вещественных чисел (тип double) с четно-нечетным слиянием Бэтчера.

---

modules/task_2/novikov_d_rectangles_method_omp/CMakeLists.txt
modules/task_2/novikov_d_rectangles_method_omp/main.cpp
modules/task_2/novikov_d_rectangles_method_omp/novikov_d_rectangles_method_omp.cpp
modules/task_2/novikov_d_rectangles_method_omp/novikov_d_rectangles_method_omp.h

Новиков Данил. Задача 2. Вычисление многомерных интегралов с использованием многошаговой схемы (метод прямоугольников) (Исправление)

---

modules/task_2/vizgalov_a_hoare_sort_simple_merge/CMakeLists.txt
modules/task_2/vizgalov_a_hoare_sort_simple_merge/hoare_sort_simple_merge.cpp
modules/task_2/vizgalov_a_hoare_sort_simple_merge/hoare_sort_simple_merge.h
modules/task_2/vizgalov_a_hoare_sort_simple_merge/main.cpp

OMP версия.
Исправлены медленные тесты (теперь макс. ~0.7 сек вместо 7 сек).

Визгалов Антон. Задача 2. Сортировка Хоара с простым слиянием (исправленная).

---

modules/task_4/vizgalov_a_hoare_sort_simple_merge/CMakeLists.txt
modules/task_4/vizgalov_a_hoare_sort_simple_merge/hoare_sort_simple_merge.cpp
modules/task_4/vizgalov_a_hoare_sort_simple_merge/hoare_sort_simple_merge.h
modules/task_4/vizgalov_a_hoare_sort_simple_merge/main.cpp

Визгалов Антон. Задача 4. Сортировка Хоара с простым слиянием.

---

modules/task_2/rachin_i_lin_hist_stret_omp/main.cpp
modules/task_3/rachin_i_lin_hist_stret_tbb/lin_hist_stret.cpp
modules/task_3/rachin_i_lin_hist_stret_tbb/main.cpp

Also some improvements of the second lab.

Рачин Игорь. Задача 3. Повышение контраста полутонового изображения посредством линейной растяжки гистограммы.
